# Generated by Django 4.2.3 on 2023-07-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_tempat_profil_dusun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='nikibu',
            field=models.IntegerField(),
        ),
    ]
